// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw-Hgmm74tmMXP7FmDLSkDVspZcXE9rb8',
    appId: '1:1073492521283:web:5ed99868c7ed7599e47ff6',
    messagingSenderId: '1073492521283',
    projectId: 'chat-app-b6b73',
    authDomain: 'chat-app-b6b73.firebaseapp.com',
    storageBucket: 'chat-app-b6b73.appspot.com',
    measurementId: 'G-L34RW9JFJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZo35iR9_JUyVOIjXdI1S1BFrs4t_W3Q',
    appId: '1:1073492521283:android:8279f5a998b9aa31e47ff6',
    messagingSenderId: '1073492521283',
    projectId: 'chat-app-b6b73',
    storageBucket: 'chat-app-b6b73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLP5Te_Wta0XSqz3M-Mc4wsmML3w6VziQ',
    appId: '1:1073492521283:ios:da9769a58ccc5c22e47ff6',
    messagingSenderId: '1073492521283',
    projectId: 'chat-app-b6b73',
    storageBucket: 'chat-app-b6b73.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
